# Generated by Django 5.0.6 on 2024-06-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('keywords', models.CharField(max_length=160)),
                ('desc', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/imgs')),
                ('status', models.IntegerField()),
                ('created', models.DateField(null=True)),
                ('updated', models.DateField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='system.category')),
            ],
        ),
    ]
