# Generated by Django 5.0.6 on 2024-07-30 10:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=150)),
                ('decription', models.CharField(max_length=256)),
                ('domain', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('past_mail', models.CharField(max_length=256)),
                ('host_mail', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/imgs/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
